# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: Hand Anatomy
  items:
    - label: "Bones"
      link: "/anatomy/bones"
    - label: "Muscles"
      link: "/anatomy/muscles"
    - label: "Pulleys"
      link: "/anatomy/pulleys"
    - label: "Flexor-pulley system"
      link: "/anatomy/pulley-system"
- label: Injury
  items:
    - label: Overview
      link: "/injury/injury-mechanics"
    - label: Risk factors
      link: /injury/risk-factors
- label: Grips
  items:
    - label: Open grip
      link: "/injury/grips/open"
    - label: Open crimp
      link: "/injury/grips/open-crimp"
    - label: Closed crimp
      link: "/injury/grips/closed-crimp"
- label: Main takeaways
  link: "/injury/grips/takeaway"
- label: Sources
  items:
    - label: Can I trust this site?
      link: /sources
