# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: Hand Anatomy
  items:
    - label: "Bones"
      link: "/anatomy/bones"
    - label: "Muscles"
      link: "/anatomy/muscles"
    - label: "Pulleys"
      link: "/anatomy/pulleys"
    - label: "Flexor-pulley system"
      link: "/anatomy/pulley-system"
- label: Injury
  items:
    - label: Injury mechanics
      link: /faq
    - label: Risk factors
      link: /changelog
- label: Sources
  items:
    - label: Can I trust this site?
      link: /changelog
